const { createElement: h, cloneElement, useEffect, useState } = React;

const navItems = [['Overview', '◈'], ['Chit groups', '◎'], ['Members', '◌'], ['Collections', '↗'], ['Auctions', '◇'], ['Ledger', '▤'], ['Reports', '▥'], ['Settings', '⚙']];
const stats = [['Total funds under management', '₹ 48,50,000', '↑ 12.8%', 'accent-blue'], ['Collections this month', '₹ 8,42,500', '↑ 6.4%', 'accent-yellow'], ['Active members', '128', '↑ 4.2%', 'accent-coral'], ['On-time payment rate', '94.6%', '↑ 2.1%', 'accent-green']];
const groups = [
  { name: 'Group Alpha', type: 'Auction chit', amount: '₹ 5,00,000', cycle: '8 / 20', collected: '₹ 3,40,000', pending: '₹ 40,000', status: 'Active' },
  { name: 'Group Beta', type: 'Fixed chit', amount: '₹ 2,50,000', cycle: '11 / 24', collected: '₹ 1,98,500', pending: '₹ 26,500', status: 'Active' },
  { name: 'Group Gamma', type: 'Loan chit', amount: '₹ 10,00,000', cycle: '4 / 12', collected: '₹ 7,60,000', pending: '₹ 90,000', status: 'Active' },
  { name: 'Group Delta', type: 'Committee', amount: '₹ 1,00,000', cycle: '18 / 20', collected: '₹ 88,000', pending: '₹ 2,000', status: 'Closing soon' }
];
const baseMembers = [
  { name: 'Ravi Kumar', group: 'Group Alpha', due: '₹ 18,750', paid: '₹ 18,750', status: 'Paid', initials: 'RK' },
  { name: 'Priya Nair', group: 'Group Delta', due: '₹ 18,750', paid: '₹ 10,000', status: 'Partial', initials: 'PN' },
  { name: 'Shivam Mehta', group: 'Group Beta', due: '₹ 12,500', paid: '₹ 0', status: 'Due', initials: 'SM' },
  { name: 'Sunitha Reddy', group: 'Group Alpha', due: '₹ 18,750', paid: '₹ 18,750', status: 'Paid', initials: 'SR' },
  { name: 'Imran Shaikh', group: 'Group Gamma', due: '₹ 25,000', paid: '₹ 25,000', status: 'Paid', initials: 'IS' }
];

function Sidebar({ active, onNavigate }) { return h('aside', { className: 'sidebar' }, h('div', { className: 'brand' }, h('span', { className: 'brand-mark' }, 'C'), h('span', null, 'ChitMate')), h('div', { className: 'workspace-switcher' }, h('span', { className: 'workspace-dot' }), h('span', null, h('small', null, 'Workspace'), h('strong', null, 'Northstar Finance')), h('span', { className: 'chevron' }, '⌄')), h('nav', { className: 'primary-nav', 'aria-label': 'Primary navigation' }, h('p', { className: 'nav-label' }, 'Workspace'), navItems.slice(0, 5).map(([name, icon]) => h('button', { key: name, className: `nav-item ${active === name ? 'active' : ''}`, onClick: () => onNavigate(name) }, h('span', { className: 'nav-icon' }, icon), name, name === 'Chit groups' && h('span', { className: 'nav-count' }, '4'))), h('p', { className: 'nav-label secondary-label' }, 'Manage'), navItems.slice(5).map(([name, icon]) => h('button', { key: name, className: `nav-item ${active === name ? 'active' : ''}`, onClick: () => onNavigate(name) }, h('span', { className: 'nav-icon' }, icon), name))), h('div', { className: 'sidebar-footer' }, h('div', { className: 'help-icon' }, '?'), h('div', null, h('strong', null, 'Need a hand?'), h('span', null, 'Visit the help center')), h('span', { className: 'arrow' }, '↗'))); }
function StatCard({ stat }) { return h('article', { className: `stat-card ${stat[3]}` }, h('div', { className: 'stat-top' }, h('span', null, stat[0]), h('span', { className: 'stat-symbol' }, '↗')), h('strong', null, stat[1]), h('div', { className: 'stat-foot' }, h('span', { className: 'positive' }, stat[2]), h('span', null, 'vs last month'))); }
function Cashflow() { return h('section', { className: 'panel cashflow-panel' }, h('div', { className: 'panel-heading' }, h('div', null, h('h2', null, 'Cash flow'), h('p', null, 'Inflow and outflow across all groups')), h('select', { 'aria-label': 'Cash flow period' }, h('option', null, 'Last 6 months'))), h('div', { className: 'chart-area' }, h('div', { className: 'chart-y' }, ['₹ 10L', '₹ 7.5L', '₹ 5L', '₹ 2.5L', '₹ 0'].map((label) => h('span', { key: label }, label))), h('div', { className: 'chart' }, h('div', { className: 'grid-line line-1' }), h('div', { className: 'grid-line line-2' }), h('div', { className: 'grid-line line-3' }), h('div', { className: 'grid-line line-4' }), h('svg', { viewBox: '0 0 720 220', preserveAspectRatio: 'none', role: 'img', 'aria-label': 'Cash flow chart' }, h('path', { className: 'area-fill', d: 'M0 180 C40 155 65 170 110 135 S175 100 225 125 S275 90 330 100 S385 130 430 84 S490 65 540 82 S600 20 650 53 S690 35 720 20 V220 H0Z' }), h('path', { className: 'line-actual', d: 'M0 180 C40 155 65 170 110 135 S175 100 225 125 S275 90 330 100 S385 130 430 84 S490 65 540 82 S600 20 650 53 S690 35 720 20' }), h('path', { className: 'line-target', d: 'M0 192 C55 175 70 150 120 158 S190 130 240 140 S315 110 360 125 S420 90 470 106 S540 65 600 77 S675 49 720 58' })), h('div', { className: 'chart-labels' }, ['Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'].map((month) => h('span', { key: month }, month))))), h('div', { className: 'chart-legend' }, h('span', null, h('i', { className: 'legend-dot actual' }), 'Collections'), h('span', null, h('i', { className: 'legend-dot target' }), 'Disbursements'), h('span', { className: 'chart-total' }, '₹ 8.42L', h('small', null, 'collected this month')))); }
function Auction() { return h('section', { className: 'panel upcoming-panel' }, h('div', { className: 'panel-heading' }, h('div', null, h('h2', null, 'Upcoming auction'), h('p', null, 'Next scheduled event')), h('button', { className: 'more-button' }, '•••')), h('div', { className: 'auction-banner' }, h('span', { className: 'auction-kicker' }, 'NEXT AUCTION'), h('strong', null, '₹ 5,00,000'), h('div', { className: 'auction-meta' }, h('span', null, 'Group Alpha · Round 06'), h('span', { className: 'auction-date' }, '18 Sep 2024'))), h('div', { className: 'countdown' }, h('div', null, h('strong', null, '06'), h('span', null, 'Days')), h('b', null, ':'), h('div', null, h('strong', null, '14'), h('span', null, 'Hours')), h('b', null, ':'), h('div', null, h('strong', null, '32'), h('span', null, 'Minutes'))), h('button', { className: 'button button-dark full-button' }, 'View auction details →')); }
function Activity({ activity }) {
  const rows = activity.map((item, index) => h('div', { className: 'activity-row', key: `${item.name}-${index}` },
    h('span', { className: `activity-avatar ${item.tone}` }, item.initials),
    h('div', null, h('strong', null, item.name), h('span', null, item.detail)),
    h('b', { className: item.amount === 'New' ? 'status-pill blue' : 'amount positive' }, item.amount)
  ));
  return h('section', { className: 'panel activity-panel' },
    h('div', { className: 'panel-heading' }, h('div', null, h('h2', null, 'Recent activity'), h('p', null, 'Latest updates from your workspace')), h('button', { className: 'text-button' }, 'View all →')),
    h('div', { className: 'activity-list' }, rows)
  );
}
function MemberModal({ onClose, onAdd }) { const [name, setName] = useState(''); const [group, setGroup] = useState('Group Alpha'); const submit = (event) => { event.preventDefault(); if (name.trim()) onAdd(name.trim(), group); }; return h('div', { className: 'modal-backdrop open', onClick: (event) => event.target === event.currentTarget && onClose() }, h('div', { className: 'modal', role: 'dialog', 'aria-modal': 'true' }, h('button', { className: 'modal-close', onClick: onClose, 'aria-label': 'Close' }, '×'), h('p', { className: 'eyebrow' }, 'New member'), h('h2', null, 'Add a member'), h('p', { className: 'modal-copy' }, 'Create a member profile to start tracking contributions.'), h('form', { onSubmit: submit }, h('label', null, 'Full name', h('input', { required: true, autoFocus: true, value: name, onChange: (event) => setName(event.target.value), placeholder: 'e.g. Meera Shah' })), h('label', null, 'Assign to group', h('select', { value: group, onChange: (event) => setGroup(event.target.value) }, groups.map((item) => h('option', { key: item.name }, item.name)))), h('button', { className: 'button button-primary full-button', type: 'submit' }, 'Create member →')))); }
function PageTitle({ eyebrow, title, copy, action }) { return h('div', { className: 'page-heading' }, h('div', null, h('p', { className: 'eyebrow' }, eyebrow), h('h1', null, title), h('p', { className: 'heading-copy' }, copy)), action); }
function Overview({ activity, onAdd }) { return h('div', { className: 'page-wrap react-page' }, h(PageTitle, { eyebrow: 'React workspace · Monday, 09 September 2024', title: 'Good morning, Arjun ✦', copy: 'Here is what is happening across your chit fund today.', action: h('button', { className: 'button button-primary', onClick: onAdd }, '＋ Add member') }), h('div', { className: 'stat-grid' }, stats.map((stat) => h(StatCard, { key: stat[0], stat }))), h('div', { className: 'dashboard-grid' }, h(Cashflow), h(Auction)), h('div', { className: 'lower-grid' }, h(Activity, { activity }), h('section', { className: 'panel reminders-panel' }, h('div', { className: 'panel-heading' }, h('div', null, h('h2', null, 'Reminders'), h('p', null, 'Things that need your attention')), h('span', { className: 'reminder-count' }, '3')), h('div', { className: 'reminder-list' }, ['5 overdue payments', 'Verify 2 new members', 'Monthly report ready'].map((item, index) => h('button', { className: 'reminder-item', key: item }, h('span', { className: `reminder-icon ${['coral', 'yellow', 'blue'][index]}` }, ['!', '◷', '▤'][index]), h('span', null, h('strong', null, item), h('small', null, 'Review workspace update')), h('span', null, '→'))))))); }
function Table({ headers, rows, renderRow }) { return h('table', { className: 'react-table' }, h('thead', null, h('tr', null, headers.map((header) => h('th', { key: header }, header)))), h('tbody', null, rows.map((row, index) => h('tr', { key: index }, renderRow(row).map((cell, cellIndex) => cloneElement(cell, { key: `${index}-${cellIndex}` })))))); }
function GroupsView({ onAddGroup }) { return h('div', { className: 'page-wrap' }, h(PageTitle, { eyebrow: 'Workspace', title: 'Chit groups', copy: 'Set rules once and let the schedule, collections, and payouts stay in sync.', action: h('button', { className: 'button button-primary', onClick: onAddGroup }, '＋ New group') }), h('div', { className: 'stat-grid' }, h(StatCard, { stat: ['Active chits', '4', '1 closing soon', 'accent-blue'] }), h(StatCard, { stat: ['Total chit value', '₹ 18,50,000', 'Across all groups', 'accent-yellow'] })), h('section', { className: 'react-view-card' }, h(Table, { headers: ['Group', 'Type', 'Cycle', 'Collected', 'Pending', 'Status'], rows: groups, renderRow: (group) => [h('td', null, h('strong', null, group.name), h('small', { className: 'table-subtext' }, group.amount)), h('td', null, group.type), h('td', null, group.cycle), h('td', null, group.collected), h('td', null, group.pending), h('td', null, h('span', { className: 'react-badge' }, group.status))] }))); }
function MembersView({ members, onAdd }) { return h('div', { className: 'page-wrap' }, h(PageTitle, { eyebrow: 'Workspace', title: 'Members', copy: 'Every member gets a clear passbook view of dues, payments, and group participation.', action: h('button', { className: 'button button-primary', onClick: onAdd }, '＋ Add member') }), h('section', { className: 'react-view-card' }, h(Table, { headers: ['Member', 'Group', 'Due this cycle', 'Paid', 'Status', 'Passbook'], rows: members, renderRow: (member) => [h('td', null, h('strong', null, member.name), h('small', { className: 'table-subtext' }, member.initials)), h('td', null, member.group), h('td', null, member.due), h('td', null, member.paid), h('td', null, h('span', { className: `react-badge ${member.status.toLowerCase()}` }, member.status)), h('td', null, h('button', { className: 'text-button' }, 'Open →'))] }))); }
function MembersView({ members, onAdd, onInvite }) { return h('div', { className: 'page-wrap' }, h(PageTitle, { eyebrow: 'Workspace', title: 'Members', copy: 'Every member gets a clear passbook view of dues, payments, and group participation.', action: h('div', { className: 'page-actions' }, h('button', { className: 'button button-dark', onClick: onInvite }, 'Invite member →'), h('button', { className: 'button button-primary', onClick: onAdd }, '＋ Add member')) }), h('section', { className: 'react-view-card' }, h(Table, { headers: ['Member', 'Group', 'Due this cycle', 'Paid', 'Status', 'Passbook'], rows: members, renderRow: (member) => [h('td', null, h('strong', null, member.name), h('small', { className: 'table-subtext' }, member.initials)), h('td', null, member.group), h('td', null, member.due), h('td', null, member.paid), h('td', null, h('span', { className: `react-badge ${member.status.toLowerCase()}` }, member.status)), h('td', null, h('button', { className: 'text-button' }, 'Open →'))] }))); }
function CollectionsView({ members, onRecord }) { return h('div', { className: 'page-wrap' }, h(PageTitle, { eyebrow: 'Workspace', title: 'Collections', copy: 'Record full, partial, advance, and arrears payments without breaking the cycle balance.', action: h('button', { className: 'button button-primary', onClick: onRecord }, '＋ Record payment') }), h('section', { className: 'react-view-card' }, h('div', { className: 'panel-heading' }, h('div', null, h('h2', null, 'Cycle 8 collections'), h('p', null, 'Group Alpha · 16 of 20 members paid')), h('span', { className: 'react-badge' }, '₹ 3,40,000 collected')), h(Table, { headers: ['Member', 'Due', 'Paid', 'Balance', 'Status'], rows: members.slice(0, 4), renderRow: (member) => [h('td', null, member.name), h('td', null, member.due), h('td', null, member.paid), h('td', null, member.status === 'Paid' ? '₹ 0' : member.due), h('td', null, h('span', { className: `react-badge ${member.status.toLowerCase()}` }, member.status))] }))); }
function PaymentModal({ members, onClose, onSave }) { const [memberId, setMemberId] = useState(''); const [amount, setAmount] = useState(''); const [status, setStatus] = useState('paid'); const [method, setMethod] = useState('cash'); const [reference, setReference] = useState(''); const submit = (event) => { event.preventDefault(); onSave({ memberId, amount, payment_status: status, payment_method: method, reference_number: reference }); }; return h('div', { className: 'modal-backdrop open', onClick: (event) => event.target === event.currentTarget && onClose() }, h('div', { className: 'modal', role: 'dialog', 'aria-modal': 'true' }, h('button', { className: 'modal-close', onClick: onClose, 'aria-label': 'Close' }, '×'), h('p', { className: 'eyebrow' }, 'Collections'), h('h2', null, 'Record payment'), h('p', { className: 'modal-copy' }, 'Capture full, partial, advance, or arrears payments with a receipt reference.'), h('form', { onSubmit: submit }, h('label', null, 'Member', h('select', { required: true, value: memberId, onChange: (event) => setMemberId(event.target.value) }, h('option', { value: '' }, 'Select member'), members.map((member) => h('option', { key: member.name, value: member.name }, member.name)))), h('label', null, 'Amount', h('input', { required: true, type: 'number', min: '1', value: amount, onChange: (event) => setAmount(event.target.value), placeholder: 'e.g. 18750' })), h('label', null, 'Payment status', h('select', { value: status, onChange: (event) => setStatus(event.target.value) }, ['paid', 'partial', 'advance', 'arrears'].map((value) => h('option', { key: value, value }, value.charAt(0).toUpperCase() + value.slice(1)))), h('label', null, 'Payment method', h('select', { value: method, onChange: (event) => setMethod(event.target.value) }, ['cash', 'upi', 'bank', 'other'].map((value) => h('option', { key: value, value }, value.toUpperCase()))), h('label', null, 'Transaction reference (optional)', h('input', { value: reference, onChange: (event) => setReference(event.target.value), placeholder: 'UPI ID or bank reference' })), h('button', { className: 'button button-primary full-button', type: 'submit' }, 'Save payment & receipt →')))); }

function MemberDashboard({ user, onSignOut }) { return h('div', { className: 'member-home' }, h('div', { className: 'member-home-mark' }, 'C'), h('p', { className: 'eyebrow' }, 'Member access'), h('h1', null, 'Your ChitMate passbook'), h('p', { className: 'heading-copy' }, `Welcome ${user.profile?.full_name || user.email}. Your dues, payments, and auction history will appear here.`), h('div', { className: 'member-summary-grid' }, h('section', { className: 'react-view-card' }, h('p', { className: 'eyebrow' }, 'Next due'), h('h2', null, '₹ 18,750'), h('p', { className: 'heading-copy' }, 'Group Alpha · Cycle 8')), h('section', { className: 'react-view-card' }, h('p', { className: 'eyebrow' }, 'Paid this cycle'), h('h2', null, '₹ 18,750'), h('p', { className: 'heading-copy' }, 'Receipt CHM-202409'))), h('button', { className: 'auth-logout', onClick: onSignOut }, 'Sign out')); }
function AuctionsView({ onRecord }) { return h('div', { className: 'page-wrap' }, h(PageTitle, { eyebrow: 'Workspace', title: 'Auctions', copy: 'Record bids, commission, dividends, and payouts with a traceable result for every member.', action: h('button', { className: 'button button-primary', onClick: onRecord }, '＋ Record auction') }), h('div', { className: 'dashboard-grid' }, h('section', { className: 'react-view-card' }, h('p', { className: 'eyebrow' }, 'Next auction'), h('h2', null, 'Group Alpha · Round 06'), h('h1', null, '₹ 5,00,000'), h('p', { className: 'heading-copy' }, '18 September 2024 · Monthly · 20 members'), h('button', { className: 'button button-dark full-button', onClick: onRecord }, 'Open auction room →')), h('section', { className: 'react-view-card' }, h('p', { className: 'eyebrow' }, 'Last result'), h('h2', null, 'Group Gamma · Round 03'), h('h1', null, '₹ 2,10,000'), h('p', { className: 'heading-copy' }, 'Winner: Anjali Shah · 12% discount'), h('span', { className: 'react-badge' }, 'Payout processed')))); }
function LedgerView({ onRecord }) { return h('div', { className: 'page-wrap' }, h(PageTitle, { eyebrow: 'Manage', title: 'Ledger', copy: 'A complete financial trail for contributions, commission, payouts, dividends, and arrears.', action: h('button', { className: 'button button-primary', onClick: onRecord }, '＋ Add entry') }), h('section', { className: 'react-view-card' }, h('div', { className: 'panel-heading' }, h('div', null, h('h2', null, 'Group Alpha · Cycle 8'), h('p', null, 'Balance calculated from every posted entry')), h('strong', null, '₹ 1,24,500')), h(Table, { headers: ['Entry', 'Credit', 'Debit', 'Reference'], rows: [['Base contributions × 16', '₹ 3,00,000', '—', 'Cycle 8'], ['Foreman commission', '—', '₹ 20,000', 'Cycle 8'], ['Auction payout · R. Babu', '—', '₹ 3,55,500', 'Payout'], ['Loan interest received', '₹ 4,000', '—', 'Loan book']], renderRow: (entry) => [h('td', null, entry[0]), h('td', { className: 'positive' }, entry[1]), h('td', { className: 'negative' }, entry[2]), h('td', null, entry[3])] }))); }
function ReportsView() { return h('div', { className: 'page-wrap' }, h(PageTitle, { eyebrow: 'Manage', title: 'Reports', copy: 'Export cycle sheets, member statements, and your full financial ledger.' }), h('div', { className: 'stat-grid' }, ['Cycle collection sheet', 'Member passbooks', 'Full ledger export', 'Auction summary'].map((report) => h('section', { className: 'react-view-card', key: report }, h('p', { className: 'eyebrow' }, 'PDF report'), h('h2', null, report), h('p', { className: 'heading-copy' }, 'Ready for review and sharing.'), h('button', { className: 'text-button' }, 'Download PDF →'))))); }
function SimpleView({ title, copy }) { return h('div', { className: 'page-wrap' }, h(PageTitle, { eyebrow: 'Manage', title, copy }), h('section', { className: 'react-view-card' }, h('h2', null, 'Workspace controls'), h('p', { className: 'heading-copy' }, 'Configure ChitMate around your fund rules, reminders, member access, and language preferences.'), h('button', { className: 'button button-primary' }, 'Save preferences'))); }

function LoginPage({ onLogin }) {
  const [mode, setMode] = useState('manager'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [creating, setCreating] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(''); try { const result = creating ? await ChitMateBackend.auth.signUp(email, password, mode) : await ChitMateBackend.auth.signIn(email, password); if (result.error) throw result.error; if (result.data?.user) onLogin(result.data.user, creating); else setError('Account created. Check your email to confirm it before signing in.'); } catch (caught) { const message = String(caught.message || '').toLowerCase(); if (message.includes('rate limit') || message.includes('too many requests')) setError('Supabase email limit reached. Wait a while before requesting another email, or use a different email address.'); else if (message.includes('email not confirmed')) setError('Confirm your email first, then sign in.'); else setError(caught.message || 'Unable to sign in. Please try again.'); } finally { setLoading(false); } };
  const demo = () => onLogin({ email: mode === 'manager' ? 'manager@chitmate.demo' : 'member@chitmate.demo', demo: true });
  return h('main', { className: 'auth-shell' }, h('section', { className: 'auth-visual' }, h('div', { className: 'auth-brand' }, h('span', { className: 'brand-mark' }, 'C'), h('strong', null, 'ChitMate')), h('div', { className: 'auth-message' }, h('p', { className: 'eyebrow' }, 'Your fund, in sync'), h('h1', null, 'Run every chit with clarity.'), h('p', null, 'Collections, auctions, member passbooks, and the ledger in one calm workspace.'))), h('section', { className: 'auth-card' }, h('p', { className: 'eyebrow' }, 'Welcome to ChitMate'), h('h2', null, creating ? 'Create your account' : 'Sign in to your workspace'), h('p', { className: 'auth-copy' }, mode === 'manager' ? 'Manage groups, payments, auctions, and reports.' : 'View your dues, payments, and passbook.'), h('div', { className: 'auth-switch' }, h('button', { className: mode === 'manager' ? 'selected' : '', onClick: () => setMode('manager'), type: 'button' }, 'Chit manager'), h('button', { className: mode === 'member' ? 'selected' : '', onClick: () => setMode('member'), type: 'button' }, 'Chit member')), h('form', { onSubmit: submit }, h('label', null, 'Email address', h('input', { type: 'email', required: true, value: email, onChange: (event) => setEmail(event.target.value), placeholder: 'you@example.com' })), h('label', null, 'Password', h('input', { type: 'password', required: true, minLength: 6, value: password, onChange: (event) => setPassword(event.target.value), placeholder: 'At least 6 characters' })), error && h('p', { className: 'auth-error' }, error), h('button', { className: 'button button-primary full-button', type: 'submit', disabled: loading }, loading ? 'Connecting...' : creating ? 'Create account →' : 'Sign in →')), !ChitMateBackend.configured && h('button', { className: 'demo-button', type: 'button', onClick: demo }, 'Preview dashboard without an account'), h('button', { className: 'auth-link', type: 'button', onClick: () => { setCreating(!creating); setError(''); } }, creating ? 'Already have an account? Sign in' : 'New to ChitMate? Create an account')));
}


function ProfilePage({ user, onComplete }) {
  const [fullName, setFullName] = useState(''); const [phone, setPhone] = useState(''); const [city, setCity] = useState(''); const [role, setRole] = useState(user.role || 'manager'); const [organizationName, setOrganizationName] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  const submit = async (event) => { event.preventDefault(); setLoading(true); setError(''); const profile = { user_id: user.id, full_name: fullName, phone, city, role, organization_name: role === 'manager' ? organizationName : null }; try { if (!user.demo) { const result = await ChitMateBackend.profiles.save(profile); if (result.error) throw result.error; } onComplete({ ...user, profile }); } catch (caught) { setError(caught.message || 'Unable to save your details.'); } finally { setLoading(false); } };
  return h('main', { className: 'auth-shell' }, h('section', { className: 'auth-visual' }, h('div', { className: 'auth-brand' }, h('span', { className: 'brand-mark' }, 'C'), h('strong', null, 'ChitMate')), h('div', { className: 'auth-message' }, h('p', { className: 'eyebrow' }, 'One last step'), h('h1', null, 'Make your workspace yours.'), h('p', null, 'Tell us a little about yourself so your ChitMate experience starts in the right place.'))), h('section', { className: 'auth-card' }, h('p', { className: 'eyebrow' }, 'Profile setup'), h('h2', null, 'Your details'), h('p', { className: 'auth-copy' }, 'These details help organizers and members find the right workspace.'), h('form', { onSubmit: submit }, h('label', null, 'Full name', h('input', { required: true, value: fullName, onChange: (event) => setFullName(event.target.value), placeholder: 'e.g. Arjun Menon' })), h('label', null, 'Phone number', h('input', { required: true, type: 'tel', value: phone, onChange: (event) => setPhone(event.target.value), placeholder: '+91 98765 43210' })), h('label', null, 'City', h('input', { required: true, value: city, onChange: (event) => setCity(event.target.value), placeholder: 'e.g. Bengaluru' })), h('label', null, 'I am joining as', h('select', { value: role, onChange: (event) => setRole(event.target.value) }, h('option', { value: 'manager' }, 'Chit manager'), h('option', { value: 'member' }, 'Chit member'))), role === 'manager' && h('label', null, 'Organization or fund name', h('input', { required: true, value: organizationName, onChange: (event) => setOrganizationName(event.target.value), placeholder: 'e.g. Northstar Finance' })), error && h('p', { className: 'auth-error' }, error), h('button', { className: 'button button-primary full-button', type: 'submit', disabled: loading }, loading ? 'Saving details...' : 'Continue to ChitMate →'))));
}
function App() {
  const [user, setUser] = useState(null); const [needsProfile, setNeedsProfile] = useState(false); const [active, setActive] = useState('Overview'); const [showMember, setShowMember] = useState(false); const [showPayment, setShowPayment] = useState(false); const [notice, setNotice] = useState(''); const [members, setMembers] = useState(baseMembers); const [activity, setActivity] = useState([{ initials: 'RK', name: 'Ravi Kumar paid installment', detail: 'Group Alpha · 15 minutes ago', amount: '+ ₹ 25,000', tone: 'teal' }, { initials: 'PN', name: 'Priya Nair joined Group Delta', detail: 'New member · 42 minutes ago', amount: 'New', tone: 'violet' }, { initials: 'SM', name: 'Shivam Mehta missed installment', detail: 'Group Beta · 1 hour ago', amount: '₹ 12,500', tone: 'orange' }, { initials: 'AS', name: 'Auction payout processed', detail: 'Group Gamma · 3 hours ago', amount: '- ₹ 2,10,000', tone: 'green' }]);
  const flash = (message) => { setNotice(message); setTimeout(() => setNotice(''), 2600); };
  const addMember = (name, group) => { const initials = name.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase(); setMembers([{ name, group, due: '₹ 18,750', paid: '₹ 0', status: 'Due', initials }, ...members]); setActivity([{ initials, name: `${name} joined ${group}`, detail: 'New member · Just now', amount: 'New', tone: 'teal' }, ...activity]); setShowMember(false); flash('Member added to ChitMate'); };
  const action = async (message) => { if (message === 'Record payment') { setShowPayment(true); return; } if (message === 'Invite member' && !user.demo) { const result = await ChitMateBackend.invites.create({ organization_id: user.profile?.organization_id, email: 'member@example.com' }); if (!result.error) flash(`Invite link created: ${location.origin}${location.pathname}?invite=${result.data.token}`); else flash(result.error.message); return; } flash(`${message} dialog is ready for your next API connection.`); };
  const restoreUser = async (signedInUser, isNew = false) => { if (!signedInUser || signedInUser.demo || isNew || !ChitMateBackend.configured) { setUser(signedInUser); setNeedsProfile(Boolean(isNew)); return; } const profileResult = await ChitMateBackend.profiles.get(signedInUser.id); setUser({ ...signedInUser, profile: profileResult.data || null }); setNeedsProfile(!profileResult.data); };
  useEffect(() => { if (!ChitMateBackend.configured) return undefined; let activeSession = true; ChitMateBackend.auth.currentUser().then((result) => { if (activeSession && result.data?.user) restoreUser(result.data.user); }); const subscription = ChitMateBackend.auth.onChange((_event, session) => { if (activeSession && session?.user) restoreUser(session.user); }); return () => { activeSession = false; subscription?.data?.subscription?.unsubscribe(); }; }, []);
  if (!user) return h(LoginPage, { onLogin: restoreUser });
  if (needsProfile) return h(ProfilePage, { user, onComplete: async (completedUser) => { if (!user.demo && completedUser.profile.role === 'manager') { const organization = await ChitMateBackend.organizations.create({ name: completedUser.profile.organization_name, owner_id: user.id }); if (!organization.error) { await ChitMateBackend.organizations.addMember({ organization_id: organization.data.id, user_id: user.id, role: 'owner' }); completedUser.profile.organization_id = organization.data.id; await ChitMateBackend.profiles.save(completedUser.profile); } } setUser(completedUser); setNeedsProfile(false); } });
  if (user.profile?.role === 'member') return h(MemberDashboard, { user, onSignOut: async () => { if (!user.demo) await ChitMateBackend.auth.signOut(); setUser(null); } });
  const content = active === 'Overview' ? h(Overview, { activity, onAdd: () => setShowMember(true) }) : active === 'Chit groups' ? h(GroupsView, { onAddGroup: () => action('New group') }) : active === 'Members' ? h(MembersView, { members, onAdd: () => setShowMember(true), onInvite: () => action('Invite member') }) : active === 'Collections' ? h(CollectionsView, { members, onRecord: () => action('Record payment') }) : active === 'Auctions' ? h(AuctionsView, { onRecord: () => action('Record auction') }) : active === 'Ledger' ? h(LedgerView, { onRecord: () => action('Ledger entry') }) : active === 'Reports' ? h(ReportsView) : h(SimpleView, { title: active, copy: 'Keep your ChitMate workspace organized and ready for the next cycle.' });
  const signOut = async () => { if (!user.demo && ChitMateBackend.configured) await ChitMateBackend.auth.signOut(); setUser(null); };
  const savePayment = async (payment) => { if (!user.demo) { const result = await ChitMateBackend.collections.createReceiptForMember({ organizationId: user.profile?.organization_id, memberName: payment.memberId, amount: Number(payment.amount), payment_status: payment.payment_status, payment_method: payment.payment_method, reference_number: payment.reference_number }); if (result.error) { flash(result.error.message); return; } flash(`Payment saved. Receipt ${result.data.reference_number}`); } else flash('Payment recorded in preview mode'); setShowPayment(false); };
  return h('div', { className: 'app-shell' }, h(Sidebar, { active, onNavigate: setActive }), h('main', { className: 'main-content' }, h('header', { className: 'topbar' }, h('div', { className: 'breadcrumb' }, h('span', null, 'Workspace'), h('b', null, '/'), h('strong', null, active)), h('div', { className: 'top-actions' }, h('button', { className: 'icon-button', 'aria-label': 'Search' }, '⌕'), h('button', { className: 'icon-button notification-button', 'aria-label': 'Notifications' }, '♢'), h('div', { className: 'profile' }, h('span', { className: 'avatar' }, 'AM'), h('span', { className: 'profile-name' }, user.email), h('button', { className: 'auth-logout', onClick: signOut }, 'Sign out')))), content), showMember && h(MemberModal, { onClose: () => setShowMember(false), onAdd: addMember }), showPayment && h(PaymentModal, { members, onClose: () => setShowPayment(false), onSave: savePayment }), notice && h('div', { className: 'toast show', role: 'status' }, notice));
}
ReactDOM.createRoot(document.getElementById('root')).render(h(App));
